name: PR Test

on:
  pull_request:

jobs:
  check:
    runs-on: ubuntu-latest

    steps:
      - name: Check secret
        env:
          TEST_MASKED: ${{ secrets.TEST_MASKED }}
        run: |
          if [ -z "$TEST_MASKED" ]; then
            echo "Secret unavailable"
          else
            echo "Secret available"
          fi
