name: Pipeline de Teste de Logs

on:
  push:
    branches: [ "main" ]

jobs:
  teste_seguranca:
    runs-on: ubuntu-latest
    environment: github-pages

    steps:
      - name: Baixar o codigo
        uses: actions/checkout@v4

      - name: Testando Limites do Filtro de Texto
        env:
          MINHA_VARIAVEL_CONFIDENCIAL: ${{ secrets.TEST_MASKED }}
        run: |
          echo "=== Teste 1: Adicionando um hifen ==="
          echo "$MINHA_VARIAVEL_CONFIDENCIAL" | sed 's/\(..\)/\1-/'

          echo "=== Teste 2: Invertendo a ordem ==="
          echo "$MINHA_VARIAVEL_CONFIDENCIAL" | rev
